-- ============================================================================
-- HostEze — full database schema
--
-- Regenerated by replaying the complete migration history (backend/migrations/
-- and backend/db/migrations/) into a clean PostgreSQL 15 database and dumping
-- the result. Covers all 28 tables the app uses (the previous hand-written
-- schema.sql only had 7 and had drifted badly from production).
--
-- To recreate a local DB:   createdb hosteze_dev && psql -d hosteze_dev -f db/schema.sql
-- To regenerate from prod:  pg_dump --schema-only --no-owner --no-privileges "$DATABASE_URL"
-- ============================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 15.15 (Homebrew)
-- Dumped by pg_dump version 15.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: link_expense_splits_to_user(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.link_expense_splits_to_user() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  -- Link by email (if provided)
  IF NEW.email IS NOT NULL THEN
    UPDATE event_expense_splits
    SET user_id = NEW.id,
        pending_email = NULL,
        pending_phone = NULL,
        pending_name = NULL
    WHERE user_id IS NULL 
      AND pending_email = NEW.email;
  END IF;
  
  -- Link by phone (if email didn't match and phone is provided)
  IF NEW.phone IS NOT NULL THEN
    UPDATE event_expense_splits
    SET user_id = NEW.id,
        pending_email = NULL,
        pending_phone = NULL,
        pending_name = NULL
    WHERE user_id IS NULL 
      AND pending_phone = NEW.phone;
  END IF;
  
  RETURN NEW;
END;
$$;


--
-- Name: update_contact_groups_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_contact_groups_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


--
-- Name: update_device_token_timestamp(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_device_token_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


--
-- Name: update_event_expenses_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_event_expenses_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


--
-- Name: update_schedule_items_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_schedule_items_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


--
-- Name: update_user_contacts_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_user_contacts_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_otp_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_otp_codes (
    identifier character varying(255) NOT NULL,
    code_hash character varying(64) NOT NULL,
    channel character varying(10) DEFAULT 'email'::character varying NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: budgets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.budgets (
    id uuid NOT NULL,
    event_id uuid NOT NULL,
    total_budget numeric(10,2) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: communications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.communications (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    event_id uuid NOT NULL,
    type character varying(50) NOT NULL,
    message text NOT NULL,
    recipient_filter character varying(50) NOT NULL,
    recipients_count integer DEFAULT 0 NOT NULL,
    sent_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    created_by uuid,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    completed_at timestamp without time zone,
    error_message text
);


--
-- Name: contact_group_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_group_members (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    group_id uuid NOT NULL,
    contact_id uuid NOT NULL,
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: contact_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_groups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    color character varying(7) DEFAULT '#6B7280'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contacts (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(50),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: device_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    player_id character varying(255) NOT NULL,
    platform character varying(20) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT device_tokens_platform_check CHECK (((platform)::text = ANY ((ARRAY['android'::character varying, 'ios'::character varying, 'web'::character varying])::text[])))
);


--
-- Name: event_expense_splits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_expense_splits (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    expense_id uuid NOT NULL,
    user_id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    settled boolean DEFAULT false,
    settled_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT event_expense_splits_amount_check CHECK ((amount >= (0)::numeric))
);


--
-- Name: event_expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_expenses (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    event_id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    description text NOT NULL,
    category character varying(50) DEFAULT 'other'::character varying NOT NULL,
    paid_by uuid NOT NULL,
    receipt_url text,
    expense_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    split_type character varying(20) DEFAULT 'equal'::character varying,
    line_items jsonb,
    CONSTRAINT event_expenses_amount_check CHECK ((amount > (0)::numeric))
);


--
-- Name: event_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_participants (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    event_id uuid NOT NULL,
    guest_id uuid NOT NULL,
    joined_at timestamp without time zone DEFAULT now(),
    profile_photo_url character varying(500),
    bio text,
    fun_fact text,
    relationship_to_host character varying(100),
    notification_enabled boolean DEFAULT true
);


--
-- Name: event_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_posts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    event_id uuid NOT NULL,
    participant_id uuid NOT NULL,
    post_type character varying(20) NOT NULL,
    content text,
    photo_url text,
    is_pinned boolean DEFAULT false,
    is_approved boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT event_posts_post_type_check CHECK (((post_type)::text = ANY ((ARRAY['message'::character varying, 'photo'::character varying, 'announcement'::character varying])::text[])))
);


--
-- Name: event_reminders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_reminders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    reminder_type character varying(20) NOT NULL,
    sent_at timestamp without time zone DEFAULT now() NOT NULL,
    recipient_count integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT event_reminders_reminder_type_check CHECK (((reminder_type)::text = ANY ((ARRAY['3_days'::character varying, '2_days'::character varying, '1_day'::character varying, '2_hours'::character varying, '5_minutes'::character varying])::text[])))
);


--
-- Name: event_schedule_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_schedule_items (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    event_id uuid NOT NULL,
    date date NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    title character varying(200) NOT NULL,
    description text,
    location character varying(200),
    category character varying(50) DEFAULT 'activity'::character varying,
    assigned_to jsonb,
    estimated_cost numeric(10,2),
    created_by uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: event_settlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_settlements (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    event_id uuid NOT NULL,
    from_user uuid NOT NULL,
    to_user uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    settled_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    notes text,
    CONSTRAINT event_settlements_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT event_settlements_check CHECK ((from_user <> to_user))
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    date timestamp without time zone,
    location character varying(500),
    description text,
    data jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    social_wall_enabled boolean DEFAULT false,
    event_type character varying(20) DEFAULT 'host'::character varying,
    organizers jsonb DEFAULT '[]'::jsonb,
    country character varying(10) DEFAULT 'US'::character varying
);


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expenses (
    id uuid NOT NULL,
    event_id uuid NOT NULL,
    category character varying(50) NOT NULL,
    description text,
    amount numeric(10,2) NOT NULL,
    vendor character varying(255),
    paid boolean DEFAULT false,
    date date DEFAULT CURRENT_DATE,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: gift_registries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gift_registries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid,
    name character varying(255) NOT NULL,
    description text,
    estimated_price numeric(10,2),
    priority character varying(50) DEFAULT 'Medium'::character varying,
    category character varying(100),
    url text,
    is_purchased boolean DEFAULT false,
    purchased_by uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: guests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guests (
    id uuid NOT NULL,
    event_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(50),
    rsvp boolean,
    attended boolean DEFAULT false,
    attended_count integer DEFAULT 0,
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    check_in_time timestamp without time zone,
    profile_photo_url character varying(500),
    bio text,
    user_id uuid,
    contact_id uuid,
    expected_party_size integer DEFAULT 1,
    actual_party_size integer DEFAULT 0
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    type character varying(50) NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    data jsonb DEFAULT '{}'::jsonb,
    read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['guest_added'::character varying, 'event_wall_post'::character varying])::text[])))
);


--
-- Name: otp_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_codes (
    phone character varying(20) NOT NULL,
    code character varying(6) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: post_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_comments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    post_id uuid NOT NULL,
    participant_id uuid NOT NULL,
    comment_text text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: post_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_likes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    post_id uuid NOT NULL,
    participant_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: reminders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reminders (
    id uuid NOT NULL,
    event_id uuid NOT NULL,
    reminder_type character varying(50) NOT NULL,
    recipient_type character varying(20) NOT NULL,
    send_at timestamp without time zone NOT NULL,
    sent boolean DEFAULT false,
    message text,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: sms_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sms_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    event_id uuid,
    recipient_phone character varying(20) NOT NULL,
    message_type character varying(50),
    status character varying(20) DEFAULT 'sent'::character varying,
    twilio_sid character varying(100),
    cost_units integer DEFAULT 1,
    sent_at timestamp without time zone DEFAULT now(),
    error_message text
);


--
-- Name: sms_usage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sms_usage (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    credits_used integer NOT NULL,
    action_type character varying(50) NOT NULL,
    recipient_count integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    id uuid NOT NULL,
    event_id uuid,
    title text NOT NULL,
    category character varying(50) DEFAULT 'planning'::character varying,
    priority character varying(20) DEFAULT 'medium'::character varying,
    status character varying(20) DEFAULT 'not-started'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: user_contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_contacts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(20),
    email character varying(255),
    notes text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_contacts_check CHECK (((phone IS NOT NULL) OR (email IS NOT NULL)))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255),
    password text NOT NULL,
    email_verified boolean DEFAULT false,
    verification_token character varying(255),
    verification_token_expires timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    phone character varying(20),
    profile_picture_url text,
    bio text,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    reset_token character varying(255),
    reset_token_expires timestamp without time zone,
    subscription_tier character varying(20) DEFAULT 'free'::character varying,
    subscription_status character varying(20) DEFAULT 'active'::character varying,
    sms_credits integer DEFAULT 0,
    event_count integer DEFAULT 0,
    revenuecat_id character varying(255),
    sms_quota_used integer DEFAULT 0,
    sms_quota_reset_date date DEFAULT CURRENT_DATE,
    CONSTRAINT user_contact_required CHECK (((email IS NOT NULL) OR (phone IS NOT NULL)))
);


--
-- Name: auth_otp_codes auth_otp_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_otp_codes
    ADD CONSTRAINT auth_otp_codes_pkey PRIMARY KEY (identifier);


--
-- Name: budgets budgets_event_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budgets
    ADD CONSTRAINT budgets_event_id_key UNIQUE (event_id);


--
-- Name: budgets budgets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budgets
    ADD CONSTRAINT budgets_pkey PRIMARY KEY (id);


--
-- Name: communications communications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.communications
    ADD CONSTRAINT communications_pkey PRIMARY KEY (id);


--
-- Name: contact_group_members contact_group_members_group_id_contact_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_group_members
    ADD CONSTRAINT contact_group_members_group_id_contact_id_key UNIQUE (group_id, contact_id);


--
-- Name: contact_group_members contact_group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_group_members
    ADD CONSTRAINT contact_group_members_pkey PRIMARY KEY (id);


--
-- Name: contact_groups contact_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_groups
    ADD CONSTRAINT contact_groups_pkey PRIMARY KEY (id);


--
-- Name: contact_groups contact_groups_user_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_groups
    ADD CONSTRAINT contact_groups_user_id_name_key UNIQUE (user_id, name);


--
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- Name: device_tokens device_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);


--
-- Name: device_tokens device_tokens_player_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_player_id_key UNIQUE (player_id);


--
-- Name: event_expense_splits event_expense_splits_expense_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_expense_splits
    ADD CONSTRAINT event_expense_splits_expense_id_user_id_key UNIQUE (expense_id, user_id);


--
-- Name: event_expense_splits event_expense_splits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_expense_splits
    ADD CONSTRAINT event_expense_splits_pkey PRIMARY KEY (id);


--
-- Name: event_expenses event_expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_expenses
    ADD CONSTRAINT event_expenses_pkey PRIMARY KEY (id);


--
-- Name: event_participants event_participants_event_id_guest_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participants
    ADD CONSTRAINT event_participants_event_id_guest_id_key UNIQUE (event_id, guest_id);


--
-- Name: event_participants event_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participants
    ADD CONSTRAINT event_participants_pkey PRIMARY KEY (id);


--
-- Name: event_posts event_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_posts
    ADD CONSTRAINT event_posts_pkey PRIMARY KEY (id);


--
-- Name: event_reminders event_reminders_event_id_reminder_type_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_reminders
    ADD CONSTRAINT event_reminders_event_id_reminder_type_key UNIQUE (event_id, reminder_type);


--
-- Name: event_reminders event_reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_reminders
    ADD CONSTRAINT event_reminders_pkey PRIMARY KEY (id);


--
-- Name: event_schedule_items event_schedule_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_schedule_items
    ADD CONSTRAINT event_schedule_items_pkey PRIMARY KEY (id);


--
-- Name: event_settlements event_settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_settlements
    ADD CONSTRAINT event_settlements_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


--
-- Name: gift_registries gift_registries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gift_registries
    ADD CONSTRAINT gift_registries_pkey PRIMARY KEY (id);


--
-- Name: guests guests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guests
    ADD CONSTRAINT guests_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: otp_codes otp_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_codes
    ADD CONSTRAINT otp_codes_pkey PRIMARY KEY (phone);


--
-- Name: post_comments post_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_comments
    ADD CONSTRAINT post_comments_pkey PRIMARY KEY (id);


--
-- Name: post_likes post_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_pkey PRIMARY KEY (id);


--
-- Name: post_likes post_likes_post_id_participant_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_post_id_participant_id_key UNIQUE (post_id, participant_id);


--
-- Name: reminders reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reminders
    ADD CONSTRAINT reminders_pkey PRIMARY KEY (id);


--
-- Name: sms_logs sms_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sms_logs
    ADD CONSTRAINT sms_logs_pkey PRIMARY KEY (id);


--
-- Name: sms_usage sms_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sms_usage
    ADD CONSTRAINT sms_usage_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: user_contacts user_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_contacts
    ADD CONSTRAINT user_contacts_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_budgets_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_budgets_event ON public.budgets USING btree (event_id);


--
-- Name: idx_communications_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_communications_created_at ON public.communications USING btree (created_at DESC);


--
-- Name: idx_communications_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_communications_event_id ON public.communications USING btree (event_id);


--
-- Name: idx_communications_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_communications_status ON public.communications USING btree (status);


--
-- Name: idx_contact_group_members_contact_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contact_group_members_contact_id ON public.contact_group_members USING btree (contact_id);


--
-- Name: idx_contact_group_members_group_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contact_group_members_group_id ON public.contact_group_members USING btree (group_id);


--
-- Name: idx_contact_groups_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contact_groups_user_id ON public.contact_groups USING btree (user_id);


--
-- Name: idx_contacts_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contacts_user_id ON public.contacts USING btree (user_id);


--
-- Name: idx_device_tokens_player_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_device_tokens_player_id ON public.device_tokens USING btree (player_id);


--
-- Name: idx_device_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_device_tokens_user_id ON public.device_tokens USING btree (user_id);


--
-- Name: idx_event_expense_splits_expense; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_expense_splits_expense ON public.event_expense_splits USING btree (expense_id);


--
-- Name: idx_event_expense_splits_settled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_expense_splits_settled ON public.event_expense_splits USING btree (settled);


--
-- Name: idx_event_expense_splits_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_expense_splits_user ON public.event_expense_splits USING btree (user_id);


--
-- Name: idx_event_expenses_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_expenses_date ON public.event_expenses USING btree (expense_date DESC);


--
-- Name: idx_event_expenses_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_expenses_event ON public.event_expenses USING btree (event_id);


--
-- Name: idx_event_expenses_paid_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_expenses_paid_by ON public.event_expenses USING btree (paid_by);


--
-- Name: idx_event_participants_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_participants_event ON public.event_participants USING btree (event_id);


--
-- Name: idx_event_participants_guest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_participants_guest ON public.event_participants USING btree (guest_id);


--
-- Name: idx_event_posts_event_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_posts_event_created ON public.event_posts USING btree (event_id, created_at DESC);


--
-- Name: idx_event_posts_participant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_posts_participant ON public.event_posts USING btree (participant_id);


--
-- Name: idx_event_reminders_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_reminders_event_id ON public.event_reminders USING btree (event_id);


--
-- Name: idx_event_reminders_sent_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_reminders_sent_at ON public.event_reminders USING btree (sent_at);


--
-- Name: idx_event_reminders_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_reminders_type ON public.event_reminders USING btree (reminder_type);


--
-- Name: idx_event_settlements_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_settlements_event ON public.event_settlements USING btree (event_id);


--
-- Name: idx_event_settlements_users; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_settlements_users ON public.event_settlements USING btree (from_user, to_user);


--
-- Name: idx_events_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_type ON public.events USING btree (event_type);


--
-- Name: idx_events_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_user_id ON public.events USING btree (user_id);


--
-- Name: idx_expenses_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expenses_category ON public.expenses USING btree (category);


--
-- Name: idx_expenses_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expenses_date ON public.expenses USING btree (date);


--
-- Name: idx_expenses_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expenses_event ON public.expenses USING btree (event_id);


--
-- Name: idx_guests_actual_party_size; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_guests_actual_party_size ON public.guests USING btree (actual_party_size);


--
-- Name: idx_guests_contact_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_guests_contact_id ON public.guests USING btree (contact_id);


--
-- Name: idx_guests_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_guests_event_id ON public.guests USING btree (event_id);


--
-- Name: idx_guests_expected_party_size; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_guests_expected_party_size ON public.guests USING btree (expected_party_size);


--
-- Name: idx_guests_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_guests_user_id ON public.guests USING btree (user_id);


--
-- Name: idx_notifications_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at DESC);


--
-- Name: idx_notifications_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_read ON public.notifications USING btree (read);


--
-- Name: idx_notifications_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);


--
-- Name: idx_notifications_user_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user_unread ON public.notifications USING btree (user_id, read) WHERE (read = false);


--
-- Name: idx_post_comments_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_comments_post ON public.post_comments USING btree (post_id, created_at DESC);


--
-- Name: idx_post_likes_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_likes_post ON public.post_likes USING btree (post_id);


--
-- Name: idx_reminders_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reminders_event ON public.reminders USING btree (event_id);


--
-- Name: idx_reminders_send_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reminders_send_at ON public.reminders USING btree (send_at) WHERE (sent = false);


--
-- Name: idx_reminders_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reminders_type ON public.reminders USING btree (reminder_type);


--
-- Name: idx_schedule_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_date ON public.event_schedule_items USING btree (date);


--
-- Name: idx_schedule_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_event ON public.event_schedule_items USING btree (event_id);


--
-- Name: idx_schedule_event_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_schedule_event_date ON public.event_schedule_items USING btree (event_id, date);


--
-- Name: idx_sms_logs_event_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sms_logs_event_id ON public.sms_logs USING btree (event_id);


--
-- Name: idx_sms_logs_sent_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sms_logs_sent_at ON public.sms_logs USING btree (sent_at);


--
-- Name: idx_sms_logs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sms_logs_status ON public.sms_logs USING btree (status);


--
-- Name: idx_sms_logs_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sms_logs_user_id ON public.sms_logs USING btree (user_id);


--
-- Name: idx_user_contacts_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_contacts_name ON public.user_contacts USING btree (name);


--
-- Name: idx_user_contacts_user_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_user_contacts_user_email ON public.user_contacts USING btree (user_id, email) WHERE (email IS NOT NULL);


--
-- Name: idx_user_contacts_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_contacts_user_id ON public.user_contacts USING btree (user_id);


--
-- Name: idx_user_contacts_user_phone; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_user_contacts_user_phone ON public.user_contacts USING btree (user_id, phone) WHERE (phone IS NOT NULL);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email) WHERE (email IS NOT NULL);


--
-- Name: idx_users_phone; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_phone ON public.users USING btree (phone) WHERE (phone IS NOT NULL);


--
-- Name: idx_users_reset_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_reset_token ON public.users USING btree (reset_token) WHERE (reset_token IS NOT NULL);


--
-- Name: idx_users_subscription; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_subscription ON public.users USING btree (subscription_tier);


--
-- Name: device_tokens device_tokens_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER device_tokens_updated_at BEFORE UPDATE ON public.device_tokens FOR EACH ROW EXECUTE FUNCTION public.update_device_token_timestamp();


--
-- Name: event_expenses event_expenses_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER event_expenses_updated_at BEFORE UPDATE ON public.event_expenses FOR EACH ROW EXECUTE FUNCTION public.update_event_expenses_updated_at();


--
-- Name: event_schedule_items schedule_items_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER schedule_items_updated_at BEFORE UPDATE ON public.event_schedule_items FOR EACH ROW EXECUTE FUNCTION public.update_schedule_items_updated_at();


--
-- Name: contact_groups trigger_contact_groups_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_contact_groups_updated_at BEFORE UPDATE ON public.contact_groups FOR EACH ROW EXECUTE FUNCTION public.update_contact_groups_updated_at();


--
-- Name: users trigger_link_expense_splits; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_link_expense_splits AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.link_expense_splits_to_user();


--
-- Name: user_contacts trigger_user_contacts_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_user_contacts_updated_at BEFORE UPDATE ON public.user_contacts FOR EACH ROW EXECUTE FUNCTION public.update_user_contacts_updated_at();


--
-- Name: users update_users_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: budgets budgets_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budgets
    ADD CONSTRAINT budgets_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: communications communications_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.communications
    ADD CONSTRAINT communications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: communications communications_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.communications
    ADD CONSTRAINT communications_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: contact_group_members contact_group_members_contact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_group_members
    ADD CONSTRAINT contact_group_members_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.user_contacts(id) ON DELETE CASCADE;


--
-- Name: contact_group_members contact_group_members_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_group_members
    ADD CONSTRAINT contact_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.contact_groups(id) ON DELETE CASCADE;


--
-- Name: contact_groups contact_groups_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_groups
    ADD CONSTRAINT contact_groups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: contacts contacts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: device_tokens device_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: event_expense_splits event_expense_splits_expense_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_expense_splits
    ADD CONSTRAINT event_expense_splits_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.event_expenses(id) ON DELETE CASCADE;


--
-- Name: event_expense_splits event_expense_splits_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_expense_splits
    ADD CONSTRAINT event_expense_splits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: event_expenses event_expenses_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_expenses
    ADD CONSTRAINT event_expenses_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: event_expenses event_expenses_paid_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_expenses
    ADD CONSTRAINT event_expenses_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(id);


--
-- Name: event_participants event_participants_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participants
    ADD CONSTRAINT event_participants_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: event_participants event_participants_guest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participants
    ADD CONSTRAINT event_participants_guest_id_fkey FOREIGN KEY (guest_id) REFERENCES public.guests(id) ON DELETE CASCADE;


--
-- Name: event_posts event_posts_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_posts
    ADD CONSTRAINT event_posts_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: event_posts event_posts_participant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_posts
    ADD CONSTRAINT event_posts_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.event_participants(id) ON DELETE CASCADE;


--
-- Name: event_reminders event_reminders_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_reminders
    ADD CONSTRAINT event_reminders_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: event_schedule_items event_schedule_items_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_schedule_items
    ADD CONSTRAINT event_schedule_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: event_schedule_items event_schedule_items_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_schedule_items
    ADD CONSTRAINT event_schedule_items_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: event_settlements event_settlements_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_settlements
    ADD CONSTRAINT event_settlements_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: event_settlements event_settlements_from_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_settlements
    ADD CONSTRAINT event_settlements_from_user_fkey FOREIGN KEY (from_user) REFERENCES public.users(id);


--
-- Name: event_settlements event_settlements_to_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_settlements
    ADD CONSTRAINT event_settlements_to_user_fkey FOREIGN KEY (to_user) REFERENCES public.users(id);


--
-- Name: events events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: expenses expenses_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: gift_registries gift_registries_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gift_registries
    ADD CONSTRAINT gift_registries_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: gift_registries gift_registries_purchased_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gift_registries
    ADD CONSTRAINT gift_registries_purchased_by_fkey FOREIGN KEY (purchased_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: guests guests_contact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guests
    ADD CONSTRAINT guests_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.user_contacts(id) ON DELETE SET NULL;


--
-- Name: guests guests_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guests
    ADD CONSTRAINT guests_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: guests guests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guests
    ADD CONSTRAINT guests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: post_comments post_comments_participant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_comments
    ADD CONSTRAINT post_comments_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.event_participants(id) ON DELETE CASCADE;


--
-- Name: post_comments post_comments_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_comments
    ADD CONSTRAINT post_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.event_posts(id) ON DELETE CASCADE;


--
-- Name: post_likes post_likes_participant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.event_participants(id) ON DELETE CASCADE;


--
-- Name: post_likes post_likes_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.event_posts(id) ON DELETE CASCADE;


--
-- Name: reminders reminders_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reminders
    ADD CONSTRAINT reminders_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: sms_logs sms_logs_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sms_logs
    ADD CONSTRAINT sms_logs_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE SET NULL;


--
-- Name: sms_logs sms_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sms_logs
    ADD CONSTRAINT sms_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: sms_usage sms_usage_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sms_usage
    ADD CONSTRAINT sms_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: tasks tasks_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- Name: user_contacts user_contacts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_contacts
    ADD CONSTRAINT user_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


