import React, { useState, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import { DollarSign, Plus, Trash2, Edit2, Check, X, TrendingUp, TrendingDown, AlertCircle } from 'lucide-react';

const CATEGORIES = [
    'Venue',
    'Catering',
    'Decorations',
    'Entertainment',
    'Photography',
    'Transportation',
    'Gifts',
    'Misc'
];

const BudgetTab = ({ event }) => {
    const { API_URL } = useApp();
    const [budget, setBudget] = useState(null);
    const [expenses, setExpenses] = useState([]);
    const [summary, setSummary] = useState(null);
    const [loading, setLoading] = useState(true);

    // Helper function to safely format currency values
    const formatCurrency = (value, decimals = 2) => {
        const num = parseFloat(value);
        return isNaN(num) ? '0.00' : num.toFixed(decimals);
    };

    // Budget form
    const [totalBudget, setTotalBudget] = useState('');
    const [showBudgetForm, setShowBudgetForm] = useState(false);

    // Expense form
    const [showExpenseForm, setShowExpenseForm] = useState(false);
    const [editingExpense, setEditingExpense] = useState(null);
    const [expenseForm, setExpenseForm] = useState({
        category: 'Venue',
        description: '',
        amount: '',
        vendor: '',
        paid: false,
        date: new Date().toISOString().split('T')[0]
    });

    // Fetch data
    useEffect(() => {
        if (event?.id) {
            fetchBudgetData();
        }
    }, [event?.id]);

    const fetchBudgetData = async () => {
        try {
            setLoading(true);
            const token = localStorage.getItem('token');
            const headers = { 'Authorization': `Bearer ${token}` };

            // Fetch budget
            const budgetRes = await fetch(`${API_URL}/events/${event.id}/budget`, { headers });
            if (budgetRes.ok) {
                const budgetData = await budgetRes.json();
                setBudget(budgetData);
                if (budgetData) {
                    setTotalBudget(budgetData.total_budget);
                }
            }

            // Fetch expenses
            const expensesRes = await fetch(`${API_URL}/events/${event.id}/expenses`, { headers });
            if (expensesRes.ok) {
                const expensesData = await expensesRes.json();

                // Handle both old and new API response formats
                const manualExpenses = Array.isArray(expensesData) ? expensesData : (expensesData.expenses || []);

                // Auto-aggregate expenses from other tabs
                const autoExpenses = [];

                // Catering Tab
                (event.catering?.items || []).forEach(item => {
                    if (parseFloat(item.cost) > 0) {
                        autoExpenses.push({
                            id: `catering-${item.id || Math.random()}`,
                            category: 'Catering',
                            description: item.name || item.item || 'Catering Item',
                            amount: parseFloat(item.cost),
                            paid: parseFloat(item.paid) || 0 > 0,
                            source: 'Catering Tab',
                            isAutoGenerated: true,
                            date: new Date().toISOString()
                        });
                    }
                });

                // Decorations Tab
                (event.decorations?.items || []).forEach(item => {
                    if (parseFloat(item.cost) > 0) {
                        autoExpenses.push({
                            id: `decorations-${item.id || Math.random()}`,
                            category: 'Decorations',
                            description: item.name || item.item || 'Decoration Item',
                            amount: parseFloat(item.cost),
                            paid: parseFloat(item.paid) || 0 > 0,
                            source: 'Decorations Tab',
                            isAutoGenerated: true,
                            date: new Date().toISOString()
                        });
                    }
                });

                // Gifts Tab
                (event.gifts?.items || []).forEach(item => {
                    if (parseFloat(item.cost) > 0) {
                        autoExpenses.push({
                            id: `gifts-${item.id || Math.random()}`,
                            category: 'Gifts',
                            description: item.name || item.item || 'Gift Item',
                            amount: parseFloat(item.cost),
                            paid: parseFloat(item.paid) || 0 > 0,
                            source: 'Gifts Tab',
                            isAutoGenerated: true,
                            date: new Date().toISOString()
                        });
                    }
                });

                // Vendors Tab
                (event.vendors || []).forEach(vendor => {
                    if (parseFloat(vendor.cost) > 0) {
                        autoExpenses.push({
                            id: `vendor-${vendor.id || Math.random()}`,
                            category: 'Vendors',
                            description: vendor.name || 'Vendor Service',
                            amount: parseFloat(vendor.cost),
                            paid: vendor.paid || false,
                            source: 'Vendors Tab',
                            isAutoGenerated: true,
                            date: new Date().toISOString(),
                            vendor: vendor.name
                        });
                    }
                });

                // Venue Tab
                if (event.venue?.totalCost && parseFloat(event.venue.totalCost) > 0) {
                    autoExpenses.push({
                        id: 'venue-cost',
                        category: 'Venue',
                        description: event.venue.name || 'Venue Rental',
                        amount: parseFloat(event.venue.totalCost),
                        paid: event.venue.deposit && parseFloat(event.venue.deposit) > 0,
                        source: 'Venue Tab',
                        isAutoGenerated: true,
                        date: new Date().toISOString()
                    });
                }

                // Merge auto-generated with manual expenses
                setExpenses([...autoExpenses, ...manualExpenses]);
            }

            // Fetch summary
            const summaryRes = await fetch(`${API_URL}/events/${event.id}/expenses/summary`, { headers });
            if (summaryRes.ok) {
                const summaryData = await summaryRes.json();
                setSummary(summaryData);
            }

        } catch (error) {
            console.error('Error fetching budget data:', error);
        } finally {
            setLoading(false);
        }
    };

    const handleCreateBudget = async () => {
        try {
            const token = localStorage.getItem('token');
            const response = await fetch(`${API_URL}/events/${event.id}/budget`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ total_budget: parseFloat(totalBudget) })
            });

            if (response.ok) {
                setShowBudgetForm(false);
                fetchBudgetData();
            }
        } catch (error) {
            console.error('Error creating budget:', error);
        }
    };

    const handleUpdateBudget = async () => {
        try {
            const token = localStorage.getItem('token');
            const response = await fetch(`${API_URL}/events/${event.id}/budget`, {
                method: 'PUT',
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ total_budget: parseFloat(totalBudget) })
            });

            if (response.ok) {
                fetchBudgetData();
            }
        } catch (error) {
            console.error('Error updating budget:', error);
        }
    };

    const handleSaveExpense = async () => {
        try {
            const token = localStorage.getItem('token');
            const url = editingExpense
                ? `${API_URL}/events/${event.id}/expenses/${editingExpense.id}`
                : `${API_URL}/events/${event.id}/expenses`;

            const response = await fetch(url, {
                method: editingExpense ? 'PUT' : 'POST',
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    ...expenseForm,
                    amount: parseFloat(expenseForm.amount)
                })
            });

            if (response.ok) {
                setShowExpenseForm(false);
                setEditingExpense(null);
                setExpenseForm({
                    category: 'Venue',
                    description: '',
                    amount: '',
                    vendor: '',
                    paid: false,
                    date: new Date().toISOString().split('T')[0]
                });
                fetchBudgetData();
            }
        } catch (error) {
            console.error('Error saving expense:', error);
        }
    };

    const handleDeleteExpense = async (expenseId) => {
        if (!confirm('Delete this expense?')) return;

        try {
            const token = localStorage.getItem('token');
            await fetch(`${API_URL}/events/${event.id}/expenses/${expenseId}`, {
                method: 'DELETE',
                headers: { 'Authorization': `Bearer ${token}` }
            });
            fetchBudgetData();
        } catch (error) {
            console.error('Error deleting expense:', error);
        }
    };

    const startEditExpense = (expense) => {
        setEditingExpense(expense);
        setExpenseForm({
            category: expense.category,
            description: expense.description || '',
            amount: expense.amount,
            vendor: expense.vendor || '',
            paid: expense.paid,
            date: expense.date?.split('T')[0] || new Date().toISOString().split('T')[0]
        });
        setShowExpenseForm(true);
    };

    // Calculate totals from all expenses (auto + manual)
    const totalExpenses = expenses.reduce((sum, exp) => sum + (parseFloat(exp.amount) || 0), 0);
    const totalBudgetAmount = budget?.total_budget || 0;
    const remaining = totalBudgetAmount - totalExpenses;
    const budgetPercentage = totalBudgetAmount > 0 ? (totalExpenses / totalBudgetAmount) * 100 : 0;
    const isOverBudget = budgetPercentage > 100;

    if (loading) {
        return <div style={{ textAlign: 'center', padding: '2rem' }}>Loading budget...</div>;
    }

    return (
        <div>
            {/* Budget Form Modal - Show at top when editing/creating */}
            {showBudgetForm && (
                <div className="card" style={{ marginBottom: '1.5rem', padding: '1.5rem', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', color: 'white' }}>
                    <h4 style={{ fontSize: '1.125rem', fontWeight: 700, marginBottom: '1rem' }}>{budget ? 'Update Budget' : 'Set Budget'}</h4>
                    <div style={{ display: 'flex', gap: '1rem' }}>
                        <input
                            type="number"
                            value={totalBudget}
                            onChange={(e) => setTotalBudget(e.target.value)}
                            placeholder="Enter total budget"
                            className="form-input"
                            style={{ flex: 1, background: 'white', color: 'var(--text-primary)' }}
                            autoFocus
                        />
                        <button onClick={budget ? handleUpdateBudget : handleCreateBudget} className="btn btn-primary" style={{ background: 'white', color: 'var(--primary)' }}>
                            <Check size={18} /> Save
                        </button>
                        <button onClick={() => setShowBudgetForm(false)} className="btn btn-secondary" style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: '1px solid white' }}>
                            <X size={18} />
                        </button>
                    </div>
                </div>
            )}

            {/* Budget Overview or Setup - Show first */}
            {budget ? (
                <div className="card" style={{ marginBottom: '1.5rem', padding: '1.5rem', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', color: 'white' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                        <h3 style={{ fontSize: '1.25rem', fontWeight: 700 }}>Budget Overview</h3>
                        <button
                            onClick={() => {
                                setTotalBudget(budget.total_budget);
                                setShowBudgetForm(true);
                            }}
                            style={{ padding: '0.5rem', border: 'none', background: 'rgba(255,255,255,0.2)', color: 'white', cursor: 'pointer', borderRadius: 'var(--radius-md)' }}
                        >
                            <Edit2 size={18} />
                        </button>
                    </div>

                    {/* Progress Bar */}
                    <div style={{ marginBottom: '1rem' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem', marginBottom: '0.5rem' }}>
                            <span>Progress</span>
                            <span style={{ fontWeight: 700 }}>{formatCurrency(budgetPercentage, 1)}%</span>
                        </div>
                        <div style={{ width: '100%', background: 'rgba(255,255,255,0.3)', borderRadius: '999px', height: '12px', overflow: 'hidden' }}>
                            <div
                                style={{
                                    height: '100%',
                                    background: isOverBudget ? '#ef4444' : 'white',
                                    width: `${Math.min(budgetPercentage, 100)}%`,
                                    transition: 'width 0.3s ease'
                                }}
                            ></div>
                        </div>
                    </div>

                    {summary?.guest_count > 0 && (
                        <div style={{ fontSize: '0.875rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                            <DollarSign size={16} />
                            <span>Cost per guest: <strong>${formatCurrency(summary.cost_per_guest)}</strong> ({summary.guest_count} guests)</span>
                        </div>
                    )}

                    {isOverBudget && (
                        <div style={{ marginTop: '1rem', padding: '0.75rem', background: 'rgba(239,68,68,0.9)', borderRadius: 'var(--radius-md)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                            <AlertCircle size={18} />
                            <span style={{ fontSize: '0.875rem', fontWeight: 600 }}>You are over budget!</span>
                        </div>
                    )}
                </div>
            ) : (
                <div className="card" style={{ padding: '3rem', textAlign: 'center', marginBottom: '1.5rem' }}>
                    <DollarSign size={48} style={{ color: 'var(--text-tertiary)', margin: '0 auto 1rem' }} />
                    <h3 style={{ fontSize: '1.25rem', fontWeight: 600, marginBottom: '0.5rem' }}>Set Your Budget</h3>
                    <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>
                        Track expenses and stay within your event budget
                    </p>
                    <button onClick={() => setShowBudgetForm(true)} className="btn btn-primary">
                        <Plus size={18} /> Set Budget
                    </button>
                </div>
            )}

            {/* Stats Cards - Show after budget overview */}
            {budget && (
                <div style={{ display: "flex", gap: "0.75rem", marginBottom: "2rem" }}>
                    <div className="card" style={{ padding: '0.75rem', flex: 1, minWidth: 0, boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)', border: '1px solid rgba(0, 0, 0, 0.05)' }}>
                        <div style={{ fontSize: '0.6875rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Total Budget</div>
                        <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--primary)' }}>
                            ${formatCurrency(totalBudgetAmount)}
                        </div>
                    </div>
                    <div className="card" style={{ padding: '0.75rem', flex: 1, minWidth: 0, boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)', border: '1px solid rgba(0, 0, 0, 0.05)' }}>
                        <div style={{ fontSize: '0.6875rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Total Expenses</div>
                        <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--warning)' }}>
                            ${formatCurrency(totalExpenses)}
                        </div>
                    </div>
                    <div className="card" style={{ padding: '0.75rem', flex: 1, minWidth: 0, boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)', border: '1px solid rgba(0, 0, 0, 0.05)' }}>
                        <div style={{ fontSize: '0.6875rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Remaining</div>
                        <div style={{ fontSize: '1.25rem', fontWeight: 700, color: isOverBudget ? 'var(--error)' : 'var(--success)' }}>
                            ${formatCurrency(remaining)}
                        </div>
                    </div>
                    <div className="card" style={{ padding: '0.75rem', flex: 1, minWidth: 0, boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)', border: '1px solid rgba(0, 0, 0, 0.05)' }}>
                        <div style={{ fontSize: '0.6875rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Expenses</div>
                        <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                            {expenses.length}
                        </div>
                    </div>
                </div>
            )}

            {/* Category Breakdown */}
            {summary?.by_category && Object.keys(summary.by_category).length > 0 && (
                <div className="card" style={{ marginBottom: '1.5rem', padding: '1.5rem' }}>
                    <h4 style={{ fontSize: '1.125rem', fontWeight: 700, marginBottom: '1rem' }}>Expenses by Category</h4>
                    <div style={{ display: 'grid', gap: '0.75rem' }}>
                        {Object.entries(summary.by_category).map(([category, amount]) => (
                            <div key={category} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem', background: 'var(--bg-secondary)', borderRadius: 'var(--radius-md)' }}>
                                <span style={{ fontWeight: 600 }}>{category}</span>
                                <span style={{ color: 'var(--warning)', fontWeight: 700 }}>${formatCurrency(amount)}</span>
                            </div>
                        ))}
                        {/* Total Row */}
                        <div style={{
                            display: 'flex',
                            justifyContent: 'space-between',
                            alignItems: 'center',
                            padding: '0.75rem',
                            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                            borderRadius: 'var(--radius-md)',
                            marginTop: '0.5rem',
                            color: 'white'
                        }}>
                            <span style={{ fontWeight: 700, fontSize: '1.0625rem' }}>Total Expenses</span>
                            <span style={{ fontWeight: 700, fontSize: '1.0625rem' }}>${formatCurrency(totalExpenses)}</span>
                        </div>
                    </div>
                </div>
            )}

            {/* Add Expense Button */}
            {budget && (
                <button
                    onClick={() => {
                        setEditingExpense(null);
                        setExpenseForm({
                            category: 'Venue',
                            description: '',
                            amount: '',
                            vendor: '',
                            paid: false,
                            date: new Date().toISOString().split('T')[0]
                        });
                        setShowExpenseForm(!showExpenseForm);
                    }}
                    className="btn btn-primary"
                    style={{ marginBottom: '1.5rem' }}
                >
                    <Plus size={18} /> Add Expense
                </button>
            )}

            {/* Expense Form */}
            {showExpenseForm && (
                <div className="card" style={{ marginBottom: '1.5rem', padding: '1.5rem', background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)', color: 'white' }}>
                    <h4 style={{ fontSize: '1.125rem', fontWeight: 700, marginBottom: '1rem' }}>{editingExpense ? 'Edit Expense' : 'Add Expense'}</h4>
                    <div style={{ display: 'grid', gap: '1rem' }}>
                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
                            <div>
                                <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.5rem' }}>Category</label>
                                <select
                                    value={expenseForm.category}
                                    onChange={(e) => setExpenseForm({ ...expenseForm, category: e.target.value })}
                                    className="form-input"
                                    style={{ background: 'white', color: 'var(--text-primary)' }}
                                >
                                    {CATEGORIES.map(cat => (
                                        <option key={cat} value={cat}>{cat}</option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.5rem' }}>Amount ($)</label>
                                <input
                                    type="number"
                                    step="0.01"
                                    value={expenseForm.amount}
                                    onChange={(e) => setExpenseForm({ ...expenseForm, amount: e.target.value })}
                                    placeholder="0.00"
                                    className="form-input"
                                    style={{ background: 'white', color: 'var(--text-primary)' }}
                                    autoFocus
                                />
                            </div>
                        </div>

                        <div>
                            <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.5rem' }}>Description</label>
                            <input
                                type="text"
                                value={expenseForm.description}
                                onChange={(e) => setExpenseForm({ ...expenseForm, description: e.target.value })}
                                placeholder="Optional description"
                                className="form-input"
                                style={{ background: 'white', color: 'var(--text-primary)' }}
                            />
                        </div>

                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
                            <div>
                                <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.5rem' }}>Vendor</label>
                                <input
                                    type="text"
                                    value={expenseForm.vendor}
                                    onChange={(e) => setExpenseForm({ ...expenseForm, vendor: e.target.value })}
                                    placeholder="Optional vendor name"
                                    className="form-input"
                                    style={{ background: 'white', color: 'var(--text-primary)' }}
                                />
                            </div>

                            <div>
                                <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.5rem' }}>Date</label>
                                <input
                                    type="date"
                                    value={expenseForm.date}
                                    onChange={(e) => setExpenseForm({ ...expenseForm, date: e.target.value })}
                                    className="form-input"
                                    style={{ background: 'white', color: 'var(--text-primary)' }}
                                />
                            </div>
                        </div>

                        <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem', fontWeight: 600 }}>
                            <input
                                type="checkbox"
                                checked={expenseForm.paid}
                                onChange={(e) => setExpenseForm({ ...expenseForm, paid: e.target.checked })}
                                style={{ width: '1rem', height: '1rem' }}
                            />
                            <span>Paid</span>
                        </label>

                        <div style={{ display: 'flex', gap: '0.75rem' }}>
                            <button onClick={handleSaveExpense} className="btn btn-primary" style={{ flex: 1, background: 'white', color: 'var(--success)' }}>
                                <Check size={18} /> {editingExpense ? 'Update' : 'Add'}
                            </button>
                            <button
                                onClick={() => {
                                    setShowExpenseForm(false);
                                    setEditingExpense(null);
                                }}
                                className="btn btn-secondary"
                                style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: '1px solid white' }}
                            >
                                <X size={18} />
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Expense List */}
            <div className="card" style={{ padding: '1.5rem' }}>
                <h4 style={{ fontSize: '1.125rem', fontWeight: 700, marginBottom: '1rem' }}>Expenses ({expenses.length})</h4>
                {expenses.length === 0 ? (
                    <div style={{ padding: '2rem', textAlign: 'center' }}>
                        <DollarSign size={40} style={{ color: 'var(--text-tertiary)', margin: '0 auto 1rem' }} />
                        <p style={{ color: 'var(--text-secondary)' }}>No expenses recorded yet</p>
                    </div>
                ) : (
                    <div style={{ display: 'grid', gap: '0.75rem' }}>
                        {expenses.map((expense) => (
                            <div key={expense.id} className="card" style={{ padding: '0.75rem', flex: 1, minWidth: 0, boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)', border: '1px solid rgba(0, 0, 0, 0.05)', background: 'var(--bg-secondary)' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '1rem' }}>
                                    <div style={{ flex: 1 }}>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', flexWrap: 'wrap' }}>
                                            <span style={{ fontWeight: 700, fontSize: '1rem' }}>{expense.category}</span>
                                            <span style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--warning)' }}>${formatCurrency(expense.amount)}</span>
                                            {expense.paid && (
                                                <span style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem', background: 'var(--success)', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: 600 }}>
                                                    Paid
                                                </span>
                                            )}
                                            {expense.source && (
                                                <span style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem', background: 'rgba(99,102,241,0.1)', color: 'var(--primary)', borderRadius: 'var(--radius-sm)', fontWeight: 600 }}>
                                                    📍 {expense.source}
                                                </span>
                                            )}
                                        </div>
                                        {expense.description && (
                                            <p style={{ fontSize: '0.6875rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>
                                                {expense.description}
                                            </p>
                                        )}
                                        <div style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)', display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
                                            {expense.vendor && <span>Vendor: {expense.vendor}</span>}
                                            <span>{new Date(expense.date).toLocaleDateString()}</span>
                                        </div>
                                    </div>
                                    {/* Only show edit/delete for manual expenses */}
                                    {!expense.isAutoGenerated && (
                                        <div style={{ display: 'flex', gap: '0.5rem' }}>
                                            <button
                                                onClick={() => startEditExpense(expense)}
                                                style={{ padding: '0.5rem', border: 'none', background: 'transparent', color: 'var(--primary)', cursor: 'pointer', borderRadius: 'var(--radius-md)' }}
                                            >
                                                <Edit2 size={16} />
                                            </button>
                                            <button
                                                onClick={() => handleDeleteExpense(expense.id)}
                                                style={{ padding: '0.5rem', border: 'none', background: 'transparent', color: 'var(--error)', cursor: 'pointer', borderRadius: 'var(--radius-md)' }}
                                            >
                                                <Trash2 size={16} />
                                            </button>
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
};

export default BudgetTab;
