import React, { useState, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import { DollarSign, Plus, Trash2, Edit2, Check, X, AlertCircle } from 'lucide-react';
import '../../pages/EventTabs.css'; // Import shared styles

const CATEGORIES = [
    'Venue',
    'Catering',
    'Decorations',
    'Entertainment',
    'Photography',
    'Transportation',
    'Gifts',
    'Misc'
];

const BudgetTab = ({ event }) => {
    const { API_URL } = useApp();
    const [budget, setBudget] = useState(null);
    const [expenses, setExpenses] = useState([]);
    const [summary, setSummary] = useState(null);
    const [loading, setLoading] = useState(true);

    // Budget form
    const [totalBudget, setTotalBudget] = useState('');
    const [showBudgetForm, setShowBudgetForm] = useState(false);

    // Expense form
    const [showExpenseForm, setShowExpenseForm] = useState(false);
    const [editingExpense, setEditingExpense] = useState(null);
    const [expenseForm, setExpenseForm] = useState({
        category: 'Venue',
        description: '',
        amount: '',
        vendor: '',
        paid: false,
        date: new Date().toISOString().split('T')[0]
    });

    // Helper: Format Currency
    const formatCurrency = (value) => {
        const num = parseFloat(value);
        return isNaN(num) ? '0.00' : num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    };

    // Fetch data
    useEffect(() => {
        if (event?.id) fetchBudgetData();
    }, [event?.id]);

    const fetchBudgetData = async () => {
        try {
            setLoading(true);
            const token = localStorage.getItem('token');
            const headers = { 'Authorization': `Bearer ${token}` };

            // Fetch budget
            const budgetRes = await fetch(`${API_URL}/events/${event.id}/budget`, { headers });
            if (budgetRes.ok) {
                const budgetData = await budgetRes.json();
                setBudget(budgetData);
                if (budgetData) {
                    setTotalBudget(budgetData.total_budget);
                }
            }

            // Fetch expenses
            const expensesRes = await fetch(`${API_URL}/events/${event.id}/expenses`, { headers });
            if (expensesRes.ok) {
                const expensesData = await expensesRes.json();
                const manualExpenses = Array.isArray(expensesData) ? expensesData : (expensesData.expenses || []);
                const autoExpenses = generateAutoExpenses(event);
                setExpenses([...autoExpenses, ...manualExpenses]);
            }

            // Fetch summary
            const summaryRes = await fetch(`${API_URL}/events/${event.id}/expenses/summary`, { headers });
            if (summaryRes.ok) {
                const summaryData = await summaryRes.json();
                setSummary(summaryData);
            }

        } catch (error) {
            console.error('Error fetching budget data:', error);
        } finally {
            setLoading(false);
        }
    };

    const generateAutoExpenses = (event) => {
        const autoExpenses = [];
        const processItems = (items, category, source) => {
            (items || []).forEach(item => {
                if (parseFloat(item.cost) > 0) {
                    autoExpenses.push({
                        id: `${category.toLowerCase()}-${item.id || Math.random()}`,
                        category: category,
                        description: item.name || item.item || `${category} Item`,
                        amount: parseFloat(item.cost),
                        paid: parseFloat(item.paid) > 0 || (item.paid === true),
                        source: source,
                        isAutoGenerated: true,
                        date: new Date().toISOString()
                    });
                }
            });
        };

        processItems(event.catering?.items, 'Catering', 'Catering Tab');
        processItems(event.decorations?.items, 'Decorations', 'Decorations Tab');
        processItems(event.gifts?.items, 'Gifts', 'Gifts Tab');

        (event.vendors || []).forEach(vendor => {
            if (parseFloat(vendor.cost) > 0) {
                autoExpenses.push({
                    id: `vendor-${vendor.id || Math.random()}`,
                    category: 'Vendors',
                    description: vendor.name || 'Vendor Service',
                    amount: parseFloat(vendor.cost),
                    paid: vendor.paid || false,
                    source: 'Vendors Tab',
                    isAutoGenerated: true,
                    date: new Date().toISOString(),
                    vendor: vendor.name
                });
            }
        });

        if (event.venue?.totalCost && parseFloat(event.venue.totalCost) > 0) {
            autoExpenses.push({
                id: 'venue-cost',
                category: 'Venue',
                description: event.venue.name || 'Venue Rental',
                amount: parseFloat(event.venue.totalCost),
                paid: event.venue.deposit && parseFloat(event.venue.deposit) > 0,
                source: 'Venue Tab',
                isAutoGenerated: true,
                date: new Date().toISOString()
            });
        }
        return autoExpenses;
    };

    // Budget Operations
    const handleBudgetSubmit = async () => {
        try {
            const token = localStorage.getItem('token');
            const method = budget ? 'PUT' : 'POST';
            const response = await fetch(`${API_URL}/events/${event.id}/budget`, {
                method,
                headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({ total_budget: parseFloat(totalBudget) })
            });
            if (response.ok) {
                setShowBudgetForm(false);
                fetchBudgetData();
            }
        } catch (error) {
            console.error('Error saving budget:', error);
        }
    };

    // Expense Operations
    const handleSaveExpense = async (e) => {
        e.preventDefault(); // Fixed: prevent form submission refresh if wrapped in form
        try {
            const token = localStorage.getItem('token');
            const url = editingExpense
                ? `${API_URL}/events/${event.id}/expenses/${editingExpense.id}`
                : `${API_URL}/events/${event.id}/expenses`;

            const response = await fetch(url, {
                method: editingExpense ? 'PUT' : 'POST',
                headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({ ...expenseForm, amount: parseFloat(expenseForm.amount) })
            });

            if (response.ok) {
                setShowExpenseForm(false);
                setEditingExpense(null);
                resetExpenseForm();
                fetchBudgetData();
            }
        } catch (error) {
            console.error('Error saving expense:', error);
        }
    };

    const handleDeleteExpense = async (expenseId) => {
        if (!confirm('Delete this expense?')) return;
        try {
            const token = localStorage.getItem('token');
            await fetch(`${API_URL}/events/${event.id}/expenses/${expenseId}`, {
                method: 'DELETE',
                headers: { 'Authorization': `Bearer ${token}` }
            });
            fetchBudgetData();
        } catch (error) {
            console.error('Error deleting expense:', error);
        }
    };

    const resetExpenseForm = () => {
        setExpenseForm({
            category: 'Venue',
            description: '',
            amount: '',
            vendor: '',
            paid: false,
            date: new Date().toISOString().split('T')[0]
        });
    };

    const startEditExpense = (expense) => {
        setEditingExpense(expense);
        setExpenseForm({
            category: expense.category,
            description: expense.description || '',
            amount: expense.amount,
            vendor: expense.vendor || '',
            paid: expense.paid,
            date: expense.date?.split('T')[0] || new Date().toISOString().split('T')[0]
        });
        setShowExpenseForm(true);
    };

    // Calculations
    const totalExpenses = expenses.reduce((sum, exp) => sum + (parseFloat(exp.amount) || 0), 0);
    const totalBudgetAmount = budget?.total_budget || 0;
    const remaining = totalBudgetAmount - totalExpenses;
    const budgetPercentage = totalBudgetAmount > 0 ? (totalExpenses / totalBudgetAmount) * 100 : 0;
    const isOverBudget = budgetPercentage > 100;

    if (loading) return <div className="tab-empty-state">Loading budget...</div>;

    return (
        <div className="event-tab-page">

            {/* Header / Empty State */}
            {!budget ? (
                <div className="tab-empty-state">
                    <div style={{ width: 64, height: 64, background: 'var(--bg-secondary)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
                        <DollarSign size={32} color="var(--primary)" />
                    </div>
                    <h3 className="section-title" style={{ marginBottom: 8 }}>Set Your Budget</h3>
                    <p style={{ marginBottom: 24 }}>Track event expenses and stay on target.</p>
                    <button
                        onClick={() => setShowBudgetForm(true)}
                        className="btn btn-primary"
                        style={{ margin: '0 auto' }}
                    >
                        Set Total Budget
                    </button>
                </div>
            ) : (
                <>
                    {/* Budget Overview Card */}
                    <div className="hero-card hero-card-event" style={{ padding: 20 }}>
                        <div className="section-header" style={{ marginBottom: 12 }}>
                            <span style={{ fontSize: 13, fontWeight: 600, opacity: 0.9 }}>BUDGET HEALTH</span>
                            <button
                                onClick={() => { setTotalBudget(budget.total_budget); setShowBudgetForm(true); }}
                                style={{ background: 'rgba(255,255,255,0.2)', border: 'none', padding: 6, borderRadius: 8, color: 'white', cursor: 'pointer' }}
                            >
                                <Edit2 size={16} />
                            </button>
                        </div>

                        <div style={{ marginBottom: 16 }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                                <span style={{ fontSize: 32, fontWeight: 700 }}>${formatCurrency(remaining)}</span>
                                <span style={{ fontSize: 14, opacity: 0.9 }}>Left of ${formatCurrency(totalBudgetAmount)}</span>
                            </div>
                        </div>

                        {/* Progress Bar */}
                        <div style={{ height: 8, background: 'rgba(255,255,255,0.2)', borderRadius: 4, overflow: 'hidden', marginBottom: 8 }}>
                            <div style={{
                                height: '100%',
                                width: `${Math.min(budgetPercentage, 100)}%`,
                                background: isOverBudget ? '#fca5a5' : 'white', /* Light red if over */
                                transition: 'width 0.5s ease'
                            }} />
                        </div>

                        {isOverBudget && (
                            <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: '#fca5a5', fontWeight: 600 }}>
                                <AlertCircle size={14} /> Only ${formatCurrency(Math.abs(remaining))} over budget
                            </div>
                        )}
                    </div>

                    {/* Stats Grid */}
                    <div className="tab-stats-grid">
                        <div className="stats-card">
                            <span style={{ fontSize: 12, color: 'var(--text-secondary)', textTransform: 'uppercase' }}>Spent</span>
                            <span style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)' }}>${formatCurrency(totalExpenses)}</span>
                        </div>
                        <div className="stats-card">
                            <span style={{ fontSize: 12, color: 'var(--text-secondary)', textTransform: 'uppercase' }}>Items</span>
                            <span style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)' }}>{expenses.length}</span>
                        </div>
                        {summary?.cost_per_guest > 0 && (
                            <div className="stats-card">
                                <span style={{ fontSize: 12, color: 'var(--text-secondary)', textTransform: 'uppercase' }}>/ Guest</span>
                                <span style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)' }}>${formatCurrency(summary.cost_per_guest)}</span>
                            </div>
                        )}
                    </div>

                    {/* Expenses List */}
                    <div className="section-header">
                        <h3 className="section-title">Expenses</h3>
                    </div>

                    <div className="tab-list">
                        {expenses.length === 0 ? (
                            <p style={{ textAlign: 'center', color: 'var(--text-tertiary)', padding: 20 }}>No expenses recorded yet.</p>
                        ) : (
                            expenses.map(expense => (
                                <div key={expense.id} className="tab-list-item">
                                    <div style={{
                                        width: 40, height: 40, borderRadius: 12,
                                        background: expense.isAutoGenerated ? 'var(--bg-tertiary)' : 'rgba(16, 185, 129, 0.1)',
                                        color: expense.isAutoGenerated ? 'var(--text-secondary)' : '#10b981',
                                        display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0
                                    }}>
                                        <DollarSign size={20} />
                                    </div>

                                    <div style={{ flex: 1, minWidth: 0 }}>
                                        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                            <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{expense.category}</span>
                                            <span style={{ fontWeight: 700, color: 'var(--text-primary)' }}>-${formatCurrency(expense.amount)}</span>
                                        </div>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, color: 'var(--text-secondary)', marginTop: 2 }}>
                                            <span style={{ truncate: true }}>{expense.description || 'No description'}</span>
                                            {expense.paid && <span style={{ color: '#10b981', fontSize: 10, fontWeight: 700, background: 'rgba(16, 185, 129, 0.1)', padding: '2px 6px', borderRadius: 4 }}>PAID</span>}
                                        </div>
                                    </div>

                                    {!expense.isAutoGenerated && (
                                        <div style={{ display: 'flex', gap: 8 }}>
                                            <button
                                                onClick={() => startEditExpense(expense)}
                                                style={{ border: 'none', background: 'transparent', color: 'var(--text-tertiary)', cursor: 'pointer', padding: 4 }}
                                            >
                                                <Edit2 size={16} />
                                            </button>
                                            <button
                                                onClick={() => handleDeleteExpense(expense.id)}
                                                style={{ border: 'none', background: 'transparent', color: '#ef4444', cursor: 'pointer', padding: 4 }}
                                            >
                                                <Trash2 size={16} />
                                            </button>
                                        </div>
                                    )}
                                </div>
                            ))
                        )}
                        <div style={{ height: 80 }} /> {/* Spacer for FAB */}
                    </div>

                    {/* FAB */}
                    <button className="btn-floating-action" onClick={() => {
                        resetExpenseForm();
                        setEditingExpense(null);
                        setShowExpenseForm(true);
                    }}>
                        <Plus size={24} />
                    </button>
                </>
            )}

            {/* Modal: Budget Form */}
            {showBudgetForm && (
                <div className="modal-overlay" onClick={() => setShowBudgetForm(false)}>
                    <div className="modal-card" onClick={e => e.stopPropagation()}>
                        <h3 className="section-title" style={{ marginBottom: 16 }}>Set Total Budget</h3>
                        <div style={{ marginBottom: 20 }}>
                            <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Target Amount ($)</label>
                            <input
                                type="number"
                                className="modern-input"
                                value={totalBudget}
                                onChange={e => setTotalBudget(e.target.value)}
                                placeholder="e.g. 5000"
                                autoFocus
                            />
                        </div>
                        <div style={{ display: 'flex', gap: 12 }}>
                            <button onClick={() => setShowBudgetForm(false)} className="btn btn-secondary" style={{ flex: 1 }}>Cancel</button>
                            <button onClick={handleBudgetSubmit} className="btn btn-primary" style={{ flex: 1 }}>Save</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Modal: Expense Form */}
            {showExpenseForm && (
                <div className="modal-overlay" onClick={() => setShowExpenseForm(false)}>
                    <div className="modal-card" onClick={e => e.stopPropagation()}>
                        <div className="section-header">
                            <h3 className="section-title">{editingExpense ? 'Edit Expense' : 'Add Expense'}</h3>
                            <button onClick={() => setShowExpenseForm(false)} style={{ border: 'none', background: 'transparent', color: 'var(--text-tertiary)' }}><X size={24} /></button>
                        </div>

                        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                                <div>
                                    <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Category</label>
                                    <select
                                        className="modern-input"
                                        value={expenseForm.category}
                                        onChange={e => setExpenseForm({ ...expenseForm, category: e.target.value })}
                                    >
                                        {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
                                    </select>
                                </div>
                                <div>
                                    <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Amount</label>
                                    <input
                                        type="number"
                                        className="modern-input"
                                        value={expenseForm.amount}
                                        onChange={e => setExpenseForm({ ...expenseForm, amount: e.target.value })}
                                        placeholder="0.00"
                                    />
                                </div>
                            </div>

                            <div>
                                <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Description</label>
                                <input
                                    className="modern-input"
                                    value={expenseForm.description}
                                    onChange={e => setExpenseForm({ ...expenseForm, description: e.target.value })}
                                    placeholder="What is this for?"
                                />
                            </div>

                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                                <div>
                                    <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Vendor (Optional)</label>
                                    <input
                                        className="modern-input"
                                        value={expenseForm.vendor}
                                        onChange={e => setExpenseForm({ ...expenseForm, vendor: e.target.value })}
                                    />
                                </div>
                                <div>
                                    <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Date</label>
                                    <input
                                        type="date"
                                        className="modern-input"
                                        value={expenseForm.date}
                                        onChange={e => setExpenseForm({ ...expenseForm, date: e.target.value })}
                                    />
                                </div>
                            </div>

                            <label style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '8px 0', cursor: 'pointer' }}>
                                <input
                                    type="checkbox"
                                    checked={expenseForm.paid}
                                    onChange={e => setExpenseForm({ ...expenseForm, paid: e.target.checked })}
                                    style={{ width: 18, height: 18 }}
                                />
                                <span style={{ color: 'var(--text-primary)', fontWeight: 500 }}>Mark as Paid</span>
                            </label>

                            <button onClick={handleSaveExpense} className="btn btn-primary" style={{ marginTop: 8 }}>
                                {editingExpense ? 'Update Expense' : 'Add Expense'}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default BudgetTab;
